### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by thedejifab**
# What Was Done
+ Allow embedded views to fix "Trying to embed a platform view but the PaintContext does not support embedding" iOS webview issue
+  match dart naming conventions for files
+  Enhance readability
+ Update README and example

### CODE REVIEW

**Comment by coolashelvetica** [comment]
@thedejifab Thanks for the PR! Do you mind fixing the conflicts? @eshiett1995 Will take a look and merge.

**Comment by thedejifab** [comment]
Oh. Sorry I was MIA. Will resolve the conflicts and push.

**Comment by thedejifab** [comment]
@coolashelvetica fixed the conflicts.

**Comment by eshiett1995** [comment]
@thedejifab taking a look at it now

**Comment by eshiett1995** [comment]
@thedejifab thank you, great job. Also thanks for the IOS webview fix. Amazing.

**Pull request merged**
